// <auto-generated/>
// Emik.SourceGenerators.Tattoo, v2.0.7
#pragma warning disable
global using global::System;
global using global::System.CodeDom;
global using global::System.CodeDom.Compiler;
global using global::System.Collections;
global using global::System.Collections.Concurrent;
global using global::System.Collections.Generic;
global using global::System.Collections.ObjectModel;
global using global::System.Collections.Specialized;
global using global::System.ComponentModel;
global using global::System.ComponentModel.Design;
global using global::System.ComponentModel.Design.Serialization;
global using global::System.Configuration;
global using global::System.Configuration.Assemblies;
global using global::System.Data;
global using global::System.Data.Common;
global using global::System.Data.Odbc;
global using global::System.Data.OleDb;
global using global::System.Data.ProviderBase;
global using global::System.Data.Sql;
global using global::System.Data.SqlClient;
global using global::System.Data.SqlTypes;
global using global::System.Deployment;
global using global::System.Deployment.Internal;
global using global::System.Deployment.Internal.Isolation;
global using global::System.Deployment.Internal.Isolation.Manifest;
global using global::System.Diagnostics;
global using global::System.Diagnostics.CodeAnalysis;
global using global::System.Diagnostics.Contracts;
global using global::System.Diagnostics.Contracts.Internal;
global using global::System.Diagnostics.Eventing;
global using global::System.Diagnostics.Eventing.Reader;
global using global::System.Diagnostics.PerformanceData;
global using global::System.Diagnostics.SymbolStore;
global using global::System.Drawing;
global using global::System.Drawing.Design;
global using global::System.Drawing.Drawing2D;
global using global::System.Drawing.Imaging;
global using global::System.Drawing.Printing;
global using global::System.Drawing.Text;
global using global::System.Dynamic;
global using global::System.Globalization;
global using global::System.IO;
global using global::System.IO.Compression;
global using global::System.IO.IsolatedStorage;
global using global::System.IO.MemoryMappedFiles;
global using global::System.IO.Pipes;
global using global::System.IO.Ports;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Management;
global using global::System.Management.Instrumentation;
global using global::System.Media;
global using global::System.Net;
global using global::System.Net.Cache;
global using global::System.Net.Configuration;
global using global::System.Net.Mail;
global using global::System.Net.Mime;
global using global::System.Net.NetworkInformation;
global using global::System.Net.Security;
global using global::System.Net.Sockets;
global using global::System.Numerics;
global using global::System.Reflection;
global using global::System.Reflection.Cache;
global using global::System.Reflection.Emit;
global using global::System.Resources;
global using global::System.Runtime;
global using global::System.Runtime.CompilerServices;
global using global::System.Runtime.ConstrainedExecution;
global using global::System.Runtime.ExceptionServices;
global using global::System.Runtime.Hosting;
global using global::System.Runtime.InteropServices;
global using global::System.Runtime.InteropServices.ComTypes;
global using global::System.Runtime.InteropServices.Expando;
global using global::System.Runtime.InteropServices.TCEAdapterGen;
global using global::System.Runtime.Remoting;
global using global::System.Runtime.Remoting.Activation;
global using global::System.Runtime.Remoting.Channels;
global using global::System.Runtime.Remoting.Contexts;
global using global::System.Runtime.Remoting.Lifetime;
global using global::System.Runtime.Remoting.Messaging;
global using global::System.Runtime.Remoting.Metadata;
global using global::System.Runtime.Remoting.Metadata.W3cXsd2001;
global using global::System.Runtime.Remoting.Proxies;
global using global::System.Runtime.Remoting.Services;
global using global::System.Runtime.Serialization;
global using global::System.Runtime.Serialization.Configuration;
global using global::System.Runtime.Serialization.Diagnostics;
global using global::System.Runtime.Serialization.Formatters;
global using global::System.Runtime.Serialization.Formatters.Binary;
global using global::System.Runtime.Serialization.Json;
global using global::System.Runtime.Versioning;
global using global::System.Security;
global using global::System.Security.AccessControl;
global using global::System.Security.Authentication;
global using global::System.Security.Authentication.ExtendedProtection;
global using global::System.Security.Authentication.ExtendedProtection.Configuration;
global using global::System.Security.Cryptography;
global using global::System.Security.Cryptography.X509Certificates;
global using global::System.Security.Permissions;
global using global::System.Security.Policy;
global using global::System.Security.Principal;
global using global::System.Security.Util;
global using global::System.StubHelpers;
global using global::System.Text;
global using global::System.Text.RegularExpressions;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::System.Timers;
global using global::System.Web;
global using global::System.Xml;
global using global::System.Xml.Linq;
global using global::System.Xml.Resolvers;
global using global::System.Xml.Schema;
global using global::System.Xml.Serialization;
global using global::System.Xml.Serialization.Advanced;
global using global::System.Xml.Serialization.Configuration;
global using global::System.Xml.XPath;
global using global::System.Xml.Xsl;
global using global::AOT;
global using global::Emik;
global using global::Emik.Morsels;
global using global::GUIBlendModes;
global using global::GlobalEnums;
global using global::HKMenu;
global using global::HutongGames;
global using global::HutongGames.Extensions;
global using global::HutongGames.PlayMaker;
global using global::HutongGames.PlayMaker.Actions;
global using global::HutongGames.PlayMaker.AnimationEnums;
global using global::HutongGames.PlayMaker.Ecosystem;
global using global::HutongGames.PlayMaker.Ecosystem.Utils;
global using global::HutongGames.Utility;
global using global::InControl;
global using global::InControl.Internal;
global using global::InControl.NativeDeviceProfiles;
global using global::InControl.UnityDeviceProfiles;
global using global::InlineMethod;
global using global::JetBrains;
global using global::JetBrains.Annotations;
global using global::Language;
global using global::MS;
global using global::MS.Internal;
global using global::MS.Internal.Xml;
global using global::MS.Internal.Xml.Cache;
global using global::MS.Internal.Xml.Linq;
global using global::MS.Internal.Xml.Linq.ComponentModel;
global using global::MS.Internal.Xml.XPath;
global using global::Microsoft;
global using global::Microsoft.CSharp;
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.Runtime;
global using global::Microsoft.Runtime.Hosting;
global using global::Microsoft.SqlServer;
global using global::Microsoft.SqlServer.Server;
global using global::Microsoft.VisualBasic;
global using global::Microsoft.Win32;
global using global::Microsoft.Win32.SafeHandles;
global using global::Microsoft.Xbox;
global using global::Modding;
global using global::Modding.Converters;
global using global::Modding.Delegates;
global using global::Modding.Menu;
global using global::Modding.Menu.Components;
global using global::Modding.Menu.Config;
global using global::Modding.Patches;
global using global::Modding.Utils;
global using global::MonoMod;
global using global::NullGuard;
global using global::ScreenShakeService;
global using global::SecPlayerPrefs;
global using global::Steamworks;
global using global::TMPro;
global using global::TeamCherry;
global using global::ToJ;
global using global::Unity;
global using global::Unity.Audio;
global using global::Unity.Baselib;
global using global::Unity.Baselib.LowLevel;
global using global::Unity.Burst;
global using global::Unity.Burst.LowLevel;
global using global::Unity.Collections;
global using global::Unity.Collections.LowLevel;
global using global::Unity.Collections.LowLevel.Unsafe;
global using global::Unity.Curl;
global using global::Unity.IL2CPP;
global using global::Unity.IL2CPP.CompilerServices;
global using global::Unity.IO;
global using global::Unity.IO.LowLevel;
global using global::Unity.IO.LowLevel.Unsafe;
global using global::Unity.Jobs;
global using global::Unity.Jobs.LowLevel;
global using global::Unity.Jobs.LowLevel.Unsafe;
global using global::Unity.Profiling;
global using global::Unity.Profiling.LowLevel;
global using global::Unity.Profiling.LowLevel.Unsafe;
global using global::Unity.Rendering;
global using global::Unity.Rendering.HybridV2;
global using global::UnityEditor;
global using global::UnityEditor.Experimental;
global using global::UnityEditor.UIElements;
global using global::UnityEngine;
global using global::UnityEngine.AI;
global using global::UnityEngine.Accessibility;
global using global::UnityEngine.Advertisements;
global using global::UnityEngine.Analytics;
global using global::UnityEngine.Android;
global using global::UnityEngine.Animations;
global using global::UnityEngine.Apple;
global using global::UnityEngine.Assertions;
global using global::UnityEngine.Assertions.Comparers;
global using global::UnityEngine.Assertions.Must;
global using global::UnityEngine.Audio;
global using global::UnityEngine.Bindings;
global using global::UnityEngine.Connect;
global using global::UnityEngine.CrashReportHandler;
global using global::UnityEngine.Diagnostics;
global using global::UnityEngine.Events;
global using global::UnityEngine.Experimental;
global using global::UnityEngine.Experimental.AI;
global using global::UnityEngine.Experimental.Animations;
global using global::UnityEngine.Experimental.AssetBundlePatching;
global using global::UnityEngine.Experimental.Audio;
global using global::UnityEngine.Experimental.GlobalIllumination;
global using global::UnityEngine.Experimental.Playables;
global using global::UnityEngine.Experimental.Rendering;
global using global::UnityEngine.Experimental.TerrainAPI;
global using global::UnityEngine.Experimental.U2D;
global using global::UnityEngine.Experimental.VFX;
global using global::UnityEngine.Experimental.Video;
global using global::UnityEngine.Experimental.XR;
global using global::UnityEngine.IO;
global using global::UnityEngine.Internal;
global using global::UnityEngine.Jobs;
global using global::UnityEngine.LowLevel;
global using global::UnityEngine.Lumin;
global using global::UnityEngine.Networking;
global using global::UnityEngine.Networking.Match;
global using global::UnityEngine.Networking.PlayerConnection;
global using global::UnityEngine.Networking.Types;
global using global::UnityEngine.ParticleSystemJobs;
global using global::UnityEngine.Playables;
global using global::UnityEngine.PlayerLoop;
global using global::UnityEngine.Profiling;
global using global::UnityEngine.Profiling.Experimental;
global using global::UnityEngine.Profiling.Memory;
global using global::UnityEngine.Profiling.Memory.Experimental;
global using global::UnityEngine.Rendering;
global using global::UnityEngine.Rendering.VirtualTexturing;
global using global::UnityEngine.SceneManagement;
global using global::UnityEngine.Scripting;
global using global::UnityEngine.Scripting.APIUpdating;
global using global::UnityEngine.SearchService;
global using global::UnityEngine.Serialization;
global using global::UnityEngine.SocialPlatforms;
global using global::UnityEngine.SocialPlatforms.Impl;
global using global::UnityEngine.Sprites;
global using global::UnityEngine.Subsystems;
global using global::UnityEngine.SubsystemsImplementation;
global using global::UnityEngine.SubsystemsImplementation.Extensions;
global using global::UnityEngine.TestTools;
global using global::UnityEngine.TextCore;
global using global::UnityEngine.TextCore.LowLevel;
global using global::UnityEngine.Tilemaps;
global using global::UnityEngine.U2D;
global using global::UnityEngine.UI;
global using global::UnityEngine.UI.Extensions;
global using global::UnityEngine.UIElements;
global using global::UnityEngine.UIElements.Experimental;
global using global::UnityEngine.UIElements.StyleSheets;
global using global::UnityEngine.UIElements.StyleSheets.Syntax;
global using global::UnityEngine.UIElements.UIR;
global using global::UnityEngine.UIElements.UIR.Implementation;
global using global::UnityEngine.VFX;
global using global::UnityEngine.Video;
global using global::UnityEngine.Windows;
global using global::UnityEngine.Windows.Speech;
global using global::UnityEngine.Windows.WebCam;
global using global::UnityEngine.XR;
global using global::UnityEngine.XR.Provider;
global using global::UnityEngine.XR.WSA;
global using global::UnityEngine.XR.WSA.Input;
global using global::UnityEngine.Yoga;
global using global::UnityEngine._Scripting;
global using global::UnityEngine._Scripting.APIUpdating;
global using global::UnityEngineInternal;
global using global::UnityEngineInternal.Input;
global using global::UnityEngineInternal.Video;
global using global::UnityEngineInternal.XR;
global using global::UnityEngineInternal.XR.WSA;
global using global::UnityStandardAssets;
global using global::UnityStandardAssets.ImageEffects;
global using global::Virtuosity;
global using global::tk2dRuntime;
global using global::tk2dRuntime.TileMap;

// Polyfills of namespaces in case dependencies are conditional.
namespace System { }

namespace System.CodeDom { }

namespace System.CodeDom.Compiler { }

namespace System.Collections { }

namespace System.Collections.Concurrent { }

namespace System.Collections.Generic { }

namespace System.Collections.ObjectModel { }

namespace System.Collections.Specialized { }

namespace System.ComponentModel { }

namespace System.ComponentModel.Design { }

namespace System.ComponentModel.Design.Serialization { }

namespace System.Configuration { }

namespace System.Configuration.Assemblies { }

namespace System.Data { }

namespace System.Data.Common { }

namespace System.Data.Odbc { }

namespace System.Data.OleDb { }

namespace System.Data.ProviderBase { }

namespace System.Data.Sql { }

namespace System.Data.SqlClient { }

namespace System.Data.SqlTypes { }

namespace System.Deployment { }

namespace System.Deployment.Internal { }

namespace System.Deployment.Internal.Isolation { }

namespace System.Deployment.Internal.Isolation.Manifest { }

namespace System.Diagnostics { }

namespace System.Diagnostics.CodeAnalysis { }

namespace System.Diagnostics.Contracts { }

namespace System.Diagnostics.Contracts.Internal { }

namespace System.Diagnostics.Eventing { }

namespace System.Diagnostics.Eventing.Reader { }

namespace System.Diagnostics.PerformanceData { }

namespace System.Diagnostics.SymbolStore { }

namespace System.Drawing { }

namespace System.Drawing.Design { }

namespace System.Drawing.Drawing2D { }

namespace System.Drawing.Imaging { }

namespace System.Drawing.Printing { }

namespace System.Drawing.Text { }

namespace System.Dynamic { }

namespace System.Globalization { }

namespace System.IO { }

namespace System.IO.Compression { }

namespace System.IO.IsolatedStorage { }

namespace System.IO.MemoryMappedFiles { }

namespace System.IO.Pipes { }

namespace System.IO.Ports { }

namespace System.Linq { }

namespace System.Linq.Expressions { }

namespace System.Management { }

namespace System.Management.Instrumentation { }

namespace System.Media { }

namespace System.Net { }

namespace System.Net.Cache { }

namespace System.Net.Configuration { }

namespace System.Net.Mail { }

namespace System.Net.Mime { }

namespace System.Net.NetworkInformation { }

namespace System.Net.Security { }

namespace System.Net.Sockets { }

namespace System.Numerics { }

namespace System.Reflection { }

namespace System.Reflection.Cache { }

namespace System.Reflection.Emit { }

namespace System.Resources { }

namespace System.Runtime { }

namespace System.Runtime.CompilerServices { }

namespace System.Runtime.ConstrainedExecution { }

namespace System.Runtime.ExceptionServices { }

namespace System.Runtime.Hosting { }

namespace System.Runtime.InteropServices { }

namespace System.Runtime.InteropServices.ComTypes { }

namespace System.Runtime.InteropServices.Expando { }

namespace System.Runtime.InteropServices.TCEAdapterGen { }

namespace System.Runtime.Remoting { }

namespace System.Runtime.Remoting.Activation { }

namespace System.Runtime.Remoting.Channels { }

namespace System.Runtime.Remoting.Contexts { }

namespace System.Runtime.Remoting.Lifetime { }

namespace System.Runtime.Remoting.Messaging { }

namespace System.Runtime.Remoting.Metadata { }

namespace System.Runtime.Remoting.Metadata.W3cXsd2001 { }

namespace System.Runtime.Remoting.Proxies { }

namespace System.Runtime.Remoting.Services { }

namespace System.Runtime.Serialization { }

namespace System.Runtime.Serialization.Configuration { }

namespace System.Runtime.Serialization.Diagnostics { }

namespace System.Runtime.Serialization.Formatters { }

namespace System.Runtime.Serialization.Formatters.Binary { }

namespace System.Runtime.Serialization.Json { }

namespace System.Runtime.Versioning { }

namespace System.Security { }

namespace System.Security.AccessControl { }

namespace System.Security.Authentication { }

namespace System.Security.Authentication.ExtendedProtection { }

namespace System.Security.Authentication.ExtendedProtection.Configuration { }

namespace System.Security.Cryptography { }

namespace System.Security.Cryptography.X509Certificates { }

namespace System.Security.Permissions { }

namespace System.Security.Policy { }

namespace System.Security.Principal { }

namespace System.Security.Util { }

namespace System.StubHelpers { }

namespace System.Text { }

namespace System.Text.RegularExpressions { }

namespace System.Threading { }

namespace System.Threading.Tasks { }

namespace System.Timers { }

namespace System.Web { }

namespace System.Xml { }

namespace System.Xml.Linq { }

namespace System.Xml.Resolvers { }

namespace System.Xml.Schema { }

namespace System.Xml.Serialization { }

namespace System.Xml.Serialization.Advanced { }

namespace System.Xml.Serialization.Configuration { }

namespace System.Xml.XPath { }

namespace System.Xml.Xsl { }

namespace AOT { }

namespace Emik { }

namespace Emik.Morsels { }

namespace GUIBlendModes { }

namespace GlobalEnums { }

namespace HKMenu { }

namespace HutongGames { }

namespace HutongGames.Extensions { }

namespace HutongGames.PlayMaker { }

namespace HutongGames.PlayMaker.Actions { }

namespace HutongGames.PlayMaker.AnimationEnums { }

namespace HutongGames.PlayMaker.Ecosystem { }

namespace HutongGames.PlayMaker.Ecosystem.Utils { }

namespace HutongGames.Utility { }

namespace InControl { }

namespace InControl.Internal { }

namespace InControl.NativeDeviceProfiles { }

namespace InControl.UnityDeviceProfiles { }

namespace InlineMethod { }

namespace JetBrains { }

namespace JetBrains.Annotations { }

namespace Language { }

namespace MS { }

namespace MS.Internal { }

namespace MS.Internal.Xml { }

namespace MS.Internal.Xml.Cache { }

namespace MS.Internal.Xml.Linq { }

namespace MS.Internal.Xml.Linq.ComponentModel { }

namespace MS.Internal.Xml.XPath { }

namespace Microsoft { }

namespace Microsoft.CSharp { }

namespace Microsoft.CodeAnalysis { }

namespace Microsoft.Runtime { }

namespace Microsoft.Runtime.Hosting { }

namespace Microsoft.SqlServer { }

namespace Microsoft.SqlServer.Server { }

namespace Microsoft.VisualBasic { }

namespace Microsoft.Win32 { }

namespace Microsoft.Win32.SafeHandles { }

namespace Microsoft.Xbox { }

namespace Modding { }

namespace Modding.Converters { }

namespace Modding.Delegates { }

namespace Modding.Menu { }

namespace Modding.Menu.Components { }

namespace Modding.Menu.Config { }

namespace Modding.Patches { }

namespace Modding.Utils { }

namespace MonoMod { }

namespace NullGuard { }

namespace ScreenShakeService { }

namespace SecPlayerPrefs { }

namespace Steamworks { }

namespace TMPro { }

namespace TeamCherry { }

namespace ToJ { }

namespace Unity { }

namespace Unity.Audio { }

namespace Unity.Baselib { }

namespace Unity.Baselib.LowLevel { }

namespace Unity.Burst { }

namespace Unity.Burst.LowLevel { }

namespace Unity.Collections { }

namespace Unity.Collections.LowLevel { }

namespace Unity.Collections.LowLevel.Unsafe { }

namespace Unity.Curl { }

namespace Unity.IL2CPP { }

namespace Unity.IL2CPP.CompilerServices { }

namespace Unity.IO { }

namespace Unity.IO.LowLevel { }

namespace Unity.IO.LowLevel.Unsafe { }

namespace Unity.Jobs { }

namespace Unity.Jobs.LowLevel { }

namespace Unity.Jobs.LowLevel.Unsafe { }

namespace Unity.Profiling { }

namespace Unity.Profiling.LowLevel { }

namespace Unity.Profiling.LowLevel.Unsafe { }

namespace Unity.Rendering { }

namespace Unity.Rendering.HybridV2 { }

namespace UnityEditor { }

namespace UnityEditor.Experimental { }

namespace UnityEditor.UIElements { }

namespace UnityEngine { }

namespace UnityEngine.AI { }

namespace UnityEngine.Accessibility { }

namespace UnityEngine.Advertisements { }

namespace UnityEngine.Analytics { }

namespace UnityEngine.Android { }

namespace UnityEngine.Animations { }

namespace UnityEngine.Apple { }

namespace UnityEngine.Assertions { }

namespace UnityEngine.Assertions.Comparers { }

namespace UnityEngine.Assertions.Must { }

namespace UnityEngine.Audio { }

namespace UnityEngine.Bindings { }

namespace UnityEngine.Connect { }

namespace UnityEngine.CrashReportHandler { }

namespace UnityEngine.Diagnostics { }

namespace UnityEngine.Events { }

namespace UnityEngine.Experimental { }

namespace UnityEngine.Experimental.AI { }

namespace UnityEngine.Experimental.Animations { }

namespace UnityEngine.Experimental.AssetBundlePatching { }

namespace UnityEngine.Experimental.Audio { }

namespace UnityEngine.Experimental.GlobalIllumination { }

namespace UnityEngine.Experimental.Playables { }

namespace UnityEngine.Experimental.Rendering { }

namespace UnityEngine.Experimental.TerrainAPI { }

namespace UnityEngine.Experimental.U2D { }

namespace UnityEngine.Experimental.VFX { }

namespace UnityEngine.Experimental.Video { }

namespace UnityEngine.Experimental.XR { }

namespace UnityEngine.IO { }

namespace UnityEngine.Internal { }

namespace UnityEngine.Jobs { }

namespace UnityEngine.LowLevel { }

namespace UnityEngine.Lumin { }

namespace UnityEngine.Networking { }

namespace UnityEngine.Networking.Match { }

namespace UnityEngine.Networking.PlayerConnection { }

namespace UnityEngine.Networking.Types { }

namespace UnityEngine.ParticleSystemJobs { }

namespace UnityEngine.Playables { }

namespace UnityEngine.PlayerLoop { }

namespace UnityEngine.Profiling { }

namespace UnityEngine.Profiling.Experimental { }

namespace UnityEngine.Profiling.Memory { }

namespace UnityEngine.Profiling.Memory.Experimental { }

namespace UnityEngine.Rendering { }

namespace UnityEngine.Rendering.VirtualTexturing { }

namespace UnityEngine.SceneManagement { }

namespace UnityEngine.Scripting { }

namespace UnityEngine.Scripting.APIUpdating { }

namespace UnityEngine.SearchService { }

namespace UnityEngine.Serialization { }

namespace UnityEngine.SocialPlatforms { }

namespace UnityEngine.SocialPlatforms.Impl { }

namespace UnityEngine.Sprites { }

namespace UnityEngine.Subsystems { }

namespace UnityEngine.SubsystemsImplementation { }

namespace UnityEngine.SubsystemsImplementation.Extensions { }

namespace UnityEngine.TestTools { }

namespace UnityEngine.TextCore { }

namespace UnityEngine.TextCore.LowLevel { }

namespace UnityEngine.Tilemaps { }

namespace UnityEngine.U2D { }

namespace UnityEngine.UI { }

namespace UnityEngine.UI.Extensions { }

namespace UnityEngine.UIElements { }

namespace UnityEngine.UIElements.Experimental { }

namespace UnityEngine.UIElements.StyleSheets { }

namespace UnityEngine.UIElements.StyleSheets.Syntax { }

namespace UnityEngine.UIElements.UIR { }

namespace UnityEngine.UIElements.UIR.Implementation { }

namespace UnityEngine.VFX { }

namespace UnityEngine.Video { }

namespace UnityEngine.Windows { }

namespace UnityEngine.Windows.Speech { }

namespace UnityEngine.Windows.WebCam { }

namespace UnityEngine.XR { }

namespace UnityEngine.XR.Provider { }

namespace UnityEngine.XR.WSA { }

namespace UnityEngine.XR.WSA.Input { }

namespace UnityEngine.Yoga { }

namespace UnityEngine._Scripting { }

namespace UnityEngine._Scripting.APIUpdating { }

namespace UnityEngineInternal { }

namespace UnityEngineInternal.Input { }

namespace UnityEngineInternal.Video { }

namespace UnityEngineInternal.XR { }

namespace UnityEngineInternal.XR.WSA { }

namespace UnityStandardAssets { }

namespace UnityStandardAssets.ImageEffects { }

namespace Virtuosity { }

namespace tk2dRuntime { }

namespace tk2dRuntime.TileMap { }
